### ISSUE TITLE
如何登陆设置内网穿透？

### ISSUE THREAD

**Issue by czweb** [TomCzHen/hassio-addons#1]
用日志里的sn和fastcode已经对应填写到szUID和szPWD里，这个UID和PWD无法在https://b.oray.com/登陆？不能登陆如何管理内网穿透？？？？？

**Comment by TomCzHen** [comment]
其实只有 SN 有用，而且这个 SN 还是绑定硬件的（初步推测是网卡物理地址）。
插件里用的 szPWD 并非帐号的密码，使用 SN 到指定页面激活，会有提示让你输入密码。
如果忘记了激活过的密码，就把 PWD 清掉之后启动插件，然后重新激活SN，已经付费激活过内网穿透则不需要再次付费（大概）。
